#!/bin/bash

TOMCAT="/home/hua/lib/tomcat7/bin"
${TOMCAT}/catalina.sh run
#cd -
# Tomcat auto-start
#
# description: Auto-starts tomcat
# processname: tomcat
# pidfile: /var/run/tomcat.pid

case $1 in
start)
sh ${TOMCAT}/catalina.sh run
;;
stop)
sh ${TOMCAT}/catalina.sh  stop -force
;;
restart)
sh ${TOMCAT}/catalina.sh stop -force
sh ${TOMCAT}/catalina.sh run
;;
esac
exit 0

